server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/nfty
    password:
    username: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    #show-sql: true

  mail:
    host: smtp.gmail.com
    port: 25
    username: email
    password: password

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 197236502867-q32vasfl07gd987vtt1aa84vshjq73n4.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

          facebook:
            clientId: 434045361635090
            clientSecret: 8d84d81d402bf90c8e6f52abd061a31b
            scope:
              - email
              - public_profile